import React from 'react';
import LegalPageLayout from '../components/LegalPageLayout';

const TermsOfServicePage: React.FC = () => {
    return (
        <LegalPageLayout title="Terms of Service">
            <p><em>Last Updated: {new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })}</em></p>

            <h2>1. Acceptance of Terms</h2>
            <p>By accessing and using AI Image Styles (the "Service"), you accept and agree to be bound by the terms and provision of this agreement. If you do not agree to abide by the above, please do not use this service.</p>
            
            <h2>2. Description of Service</h2>
            <p>The Service allows users to upload images and apply AI-powered stylistic templates to generate new images. The quality and nature of the output are dependent on the input images and the AI model's capabilities.</p>

            <h2>3. User Conduct</h2>
            <p>You agree not to use the Service to:</p>
            <ul>
                <li>Upload, post, or otherwise transmit any content that is unlawful, harmful, threatening, abusive, harassing, defamatory, vulgar, obscene, or otherwise objectionable.</li>
                <li>Upload any content that you do not have a right to transmit under any law or under contractual or fiduciary relationships.</li>
                <li>Violate any applicable local, state, national or international law.</li>
            </ul>
            
            <h2>4. Intellectual Property</h2>
            <p>You retain all ownership rights to the images you upload. By using the Service, you grant us a worldwide, non-exclusive, royalty-free license to use, reproduce, process, and display your images solely for the purpose of providing and improving the Service. You are responsible for the content you upload and must ensure you have the necessary rights.</p>

            <h2>5. Disclaimer of Warranties</h2>
            <p>The service is provided "as is". We make no warranty that the service will meet your requirements or be available on an uninterrupted, secure, or error-free basis. The results generated by the AI may be unpredictable and are not guaranteed to be accurate or satisfactory.</p>
            
            <h2>6. Limitation of Liability</h2>
            <p>In no event shall we be liable for any indirect, incidental, special, consequential or punitive damages, including without limitation, loss of profits, data, use, goodwill, or other intangible losses, resulting from your access to or use of or inability to access or use the service.</p>
            
            <h2>7. Changes to Terms</h2>
            <p>We reserve the right to modify these terms from time to time at our sole discretion. Therefore, you should review this page periodically.</p>
        </LegalPageLayout>
    );
};

export default TermsOfServicePage;